torchrun --nnodes=1 --nproc_per_node=1 train.py \
	--image_dir_path ../datasets/images/ \
	--output_dir ../output/ \
	--json_file ../datasets/images.json \
        --diffusion_model_path '/home/liying/Desktop/stable-diffusion-inpainting' \
        --draw_box \
	--lr 5e-3 \
	--max_window_size 10 \
	--per_image_iteration 10 \
	--epochs 1 \
	--num_workers 8 \
	--seed 42 \
	--pin_mem \
	--point_number 9 \
	--batch_size 1 \
	--save_path ../checkpoints/
